"""empty message

Revision ID: 417ea1b1b8fe
Revises: a29712021345
Create Date: 2020-04-13 16:59:13.380524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417ea1b1b8fe'
down_revision = 'a29712021345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activitieslogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('activities', sa.Text(), nullable=False),
    sa.Column('activities_date', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activitieslogs')
    # ### end Alembic commands ###
